### ISSUE TITLE
P-TET-000009 Front port cover - Design Updates

### ISSUE THREAD

**Issue by mechatroniks-git** [helpfulengineering/project-tetra#103]
- [x] Open up holes to allow ISO5356 22M port to clear
- [x] Add part # to model

**Comment by Judoguy12** [comment]
@mechatroniks-git Where is this part located?

**Comment by mechatroniks-git** [comment]
In the main assembly, it's the 4 dual port covers where the inspiratory/expiratory connections are

**Comment by Judoguy12** [comment]
Updated and ready for review @mechatroniks-git

**Comment by mechatroniks-git** [comment]
@Judoguy12 The hole is still too small. 
![image](https://user-images.githubusercontent.com/57600622/88407407-ec2e7200-cd86-11ea-92a1-cc1dcf326664.png)


Here is the ISO Spec 
![image](https://user-images.githubusercontent.com/57600622/88407262-b9847980-cd86-11ea-8d75-155b203e5ec4.png)

**Comment by Judoguy12** [comment]
Done @mechatroniks-git

**Comment by mmroden** [comment]
Patrick will review, John will approve

**Comment by Burhan-Q** [comment]
PEER check - Port diameters are 22.75mm and have enough space between to allow for 2" filters
