### ISSUE TITLE
P-TET-000020 Tetra Shutoff Valve Cap needs clearance

### ISSUE THREAD

**Issue by mechatroniks-git** [helpfulengineering/project-tetra#115]
Valve cap needs following tweaks
- [ ] Clearance to fit onto valve body P-TET-000023 & P-TET-000018
- [ ] Clearance to fit over the P-TET-000019 without binding
- [ ] Clearance to allow P-TET-000021 to freely rotate

Some of this may be due to printing imperfections, but the design should easily accommodate imperfect printing while allowing functionality. 

![image](https://user-images.githubusercontent.com/57600622/89335274-a73ef100-d64c-11ea-904c-174145becf94.png)

It appears that the current Fusion model has clearance, but the -0 part I printed does not. Need to make sure what is in Fusion is not the same as the -0, then add the necessary clearance (3rd item on lis) and release part for printing. 

![image](https://user-images.githubusercontent.com/57600622/89335442-de150700-d64c-11ea-8fbe-c081028316b4.png)

**Comment by jgrano** [comment]
@mechatroniks-git did you pull the part from the spread sheet or the main model? I uploaded the parts, printed on high resolution on a taz5 with abs and it went together smoothly for me.

**Comment by Burhan-Q** [comment]
@mechatroniks-git something weird is happening the assembly model when you open it. The handle is positioned as such when first opened (like in your image above)
![image](https://user-images.githubusercontent.com/62214284/89341740-c3a05500-d66f-11ea-832a-f60575e9a0c6.png)

But this position is incorrect, and if you move the handle with a click and drag, you'll notice the cap flips to the correct orientation.
![image](https://user-images.githubusercontent.com/62214284/89341941-0f52fe80-d670-11ea-8d32-b9817fd22315.png)

No more overlapping parts when viewing cross section
![image](https://user-images.githubusercontent.com/62214284/89341998-285baf80-d670-11ea-80e5-18048452d6ba.png)

**Comment by mechatroniks-git** [comment]
I've only printed the -0 part. 

The latest knob has a max dia of 21.57 - 21.54, depending on the measuring spot. The design is 21.50, so I'm a bit oversized, but well within tolerance. 

![image](https://user-images.githubusercontent.com/57600622/89345034-ad889980-d65b-11ea-8d5f-ab7a77853cdd.png)

The  mating part is also at 21.50, and should be 21.7. I can adjust the design and print.

![image](https://user-images.githubusercontent.com/57600622/89345230-f0e30800-d65b-11ea-826b-f2a7abb8cef2.png)

**Comment by mechatroniks-git** [comment]
Printing this one now
![image](https://user-images.githubusercontent.com/57600622/89347195-289f7f00-d65f-11ea-8e89-4bd2202da0b2.png)

I gave it a bit more clearance, 21.9, my printer doesn't hold tight tolerances.

**Comment by Burhan-Q** [comment]
@mechatroniks-git should this issue get updated to Testing?

**Comment by mechatroniks-git** [comment]
The -2 part feels good to me. Little bit of vertical play in the valve assembly, maybe .3mm, but probably acceptable. 

I think testing is done, ready for review @Burhan-Q 

![image](https://user-images.githubusercontent.com/57600622/89350987-ee85ab80-d665-11ea-971f-93b52be0500f.png)

**Comment by Burhan-Q** [comment]
> Valve cap needs following tweaks
> 
> * [x]  Clearance to fit onto valve body P-TET-000023 & P-TET-000018
> * [x]  Clearance to fit over the P-TET-000019 without binding
> * [x]  Clearance to allow P-TET-000021 to freely rotate

@mechatroniks-git looks like you accomplished the two items above (based on your most recent comment). Not sure if there was a typo on the first bullet point P-TET-000023 is the Tetra valve and is not related to the shutoff valve cap, assuming you meant the shutoff valve body and knob P-TET000018 and P-TET-000021 respectively. 

All else looks good, expect the filename needs to be updated to match the revision number -02. Once complete, ready for approval @jgrano.

**Comment by jgrano** [comment]
Looks awesome guys

**Comment by Burhan-Q** [comment]
> Looks awesome guys

Closing ticket

**Comment by Burhan-Q** [comment]
Reopened since file needs to be added to repo. Moved "Closed" bucket on Project board since work is complete otherwise

**Comment by mmroden** [comment]
if the file isn't in the repo, then the ticket is not closable.
