### ISSUE TITLE
P-TET-000033 Rear port cover

### ISSUE THREAD

**Issue by Burhan-Q** [helpfulengineering/project-tetra#124]
Need to create Rear port cover part.

It will be a housing cover plate for rear ports adapters that connect to ventilator #123

**Comment by Burhan-Q** [comment]
This ticket was opened after the work by @jgrano was completed. Creating ticket separate from the Rear port adapters #123 which was initially established for creation of rear cover

**Comment by Burhan-Q** [comment]
### Notes ###
- Openings cut at angle to match housing rear panel
- No apparent mechanism designed for attaching plate to housing, options: bond with epoxy, glue, or drill and screw
- Clearance between ports and opening ~2 mm
- No part number embossed on body
- Status (per week of August 24, 2020)
    - [ ] Ready for review
    - [ ] Design requires more updates

**Rear port cover**
![image](https://user-images.githubusercontent.com/62214284/91089953-50f91880-e622-11ea-9c0a-bb450c4d4de4.png)

**Port clearance**
![image](https://user-images.githubusercontent.com/62214284/91090445-12b02900-e623-11ea-9077-3cfbc378e598.png)

**Comment by Burhan-Q** [comment]
@mechatroniks-git made some modifications to the design and iterated to P-TET-000033-1 (see image). He will also be printing this for the Alpha build, so the Assignment for this issue has been updated and the [G-Sheet](https://docs.google.com/spreadsheets/d/1FWTYRxglWDqIK_xI6HlBGKUegICQRsXe5NHCJTlTlHs/edit#gid=563995584&range=A1) will also reflect this. These details come from a Slack DM at ~1700-1715 EDT on August 26, 2020.

![image](https://user-images.githubusercontent.com/62214284/91358844-8851fb80-e7c1-11ea-9938-b3257c358b85.png)

**Comment by mmroden** [comment]
Good for now, will reopen if we need it
