### ISSUE TITLE
Add capacitor to PCB

### ISSUE THREAD

**Issue by Judoguy12** [helpfulengineering/project-tetra#134]
It was mentioned that the PCB needs an extra capacitor to fix a problem

**Comment by hydronics2** [comment]
added 33nf capacitor based on the updated data sheet for the 5V regulator
https://github.com/tetrabiodistributed/project-tetra/pull/135

**Comment by mechatroniks-git** [comment]
5V regulator has been replaced with new device, this is no longer an issue
