### ISSUE TITLE
Get the Reqirements Document for Tetra

### ISSUE THREAD

**Issue by Judoguy12** [helpfulengineering/project-tetra#139]
Get the document stating the goals of Tetra

**Comment by Judoguy12** [comment]
Initial website page that will need tidying up 
https://tetrabiodistributed.github.io/project-tetra-docs/references/hardware-requirements/

**Comment by Burhan-Q** [comment]
@Judoguy12 also see this page:
https://tetrabiodistributed.github.io/project-tetra-docs/references/stakeholder-concerns-and-requirements/

**Comment by Burhan-Q** [comment]
@Judoguy12 also, these tickets might be good to relocate into the /tetrabiodistributed/project-tetra-docs/ repo
