### ISSUE TITLE
Get the Mechanical test document

### ISSUE THREAD

**Issue by Judoguy12** [helpfulengineering/project-tetra#142]
Find the document of tests needed to run on the Tetra device to ensure it is mechanically sound

**Comment by Judoguy12** [comment]
This needs writing considering testing the software and the leak of the device. Previously a ventilator was used so a solution may be needed to avoid this.

**Comment by Judoguy12** [comment]
https://docs.google.com/document/d/1d5qQ5dmPzwSBTMPdLzqYaVzz-wIni7c2SQICvF_ySZA/edit?usp=sharing

**Comment by Judoguy12** [comment]
Superceded by https://docs.google.com/document/d/15b1f-CKBMfO2Kmck0VQR8wqceb-19cEREcwgl8lF6Rk/edit?usp=drivesdk

**Comment by mmroden** [comment]
Needs a PR, not in git yet
