### ISSUE TITLE
Missing item on Pi HAT BOM

### ISSUE THREAD

**Issue by darraghbr** [helpfulengineering/project-tetra#159]
We are missing the 2x20 header strip that goes between the Pi and the HAT. 

I think this is roughly the correct part number.

https://www.mouser.co.uk/ProductDetail/TE-Connectivity/2-534998-0/?qs=%2Fha2pyFaduiXhbXo1Q7kVEqN1S1BJj7DwXrciKekKYCi1xy6LVwXqQ==&utm_source=octopart&utm_medium=aggregator&utm_campaign=571-25349980&utm_content=TE+Connectivity

**Comment by darraghbr** [comment]
@mechatroniks-git

**Comment by hydronics2** [comment]
That looks right to me. This is the one I used: https://lcsc.com/product-detail/Pin-Header-Female-Header_BOOMELE-Boom-Precision-Elec-C50982_C50982.html

**Comment by mechatroniks-git** [comment]
The TE part will work just fine. 
![image](https://user-images.githubusercontent.com/57600622/106517578-89343b00-648d-11eb-80c0-2da2a93179ba.png)
