### ISSUE TITLE
[Hardware] pushfit adapters to 22mm

### ISSUE THREAD

**Issue by mmroden** [helpfulengineering/project-tetra#168]
### Creating a task using this template
1. Rename Task title
2. Add details of task
3. Add reference of any existing Issue
4. Expand checklist below (if needed)
5. Add/Create appropriate label(s)
6. Select Project
7. Add/Create Milestone
8. Add any Assignee(s)

Task details
#(related issue number)

- [ ] Assigned _(specify assignees)_
- [ ] Work in Progress _(move card on Project Board)_
- [ ] Submit for Review _(assign reviewer, comment, & move on Project Board)_
- [ ] Working on Review changes _(comment w/ list of changes and date)_
- [ ] Review complete _(assigned reviewer comment with approved date)_

**Comment by Judoguy12** [comment]
I have just tested plastic threaded adaptors and they seem to fit together with the threaded part well now Ill move onto testing pressure drop across the pipe

**Comment by Judoguy12** [comment]
![PXL_20210821_172928145 MP](https://user-images.githubusercontent.com/30008485/130330272-04572ef8-d21e-4f95-a6ed-a4f48c803155.jpg)
