### ISSUE TITLE
[Hardware] 3D printed adapters showing signs of leakage

### ISSUE THREAD

**Issue by darraghbr** [helpfulengineering/project-tetra#181]
A significant leak has been observed on the current iteration of the push fit system.

It is suspected that it is coming from an FDM printed adapter between the push fit parts and the VentMon.

We need to identify the leaks exact location and remediate as we go. 

@Judoguy12 please use this issue to document where you locate the leaks and we will go from there.

I have pre-emptively redesigned the Sensirion adapters so they will effectively be an interference fit on the Sensirions and have printed some in a flexible resin (Photocentric Flexible LCD) these appear to seal to the Sensirions very well (so much so that I can fire the PCB clean off if I dead head it and blow hard into it)

![image](https://user-images.githubusercontent.com/31858409/135770662-e2159c1f-499c-4eb4-86fc-4982fa55943e.png)

In this image the purple is our adapter, and the cyan is the Sensirion.

I will be publishing these files in a new branch but keeping the PR as a draft.

**Comment by darraghbr** [comment]
Honestly using the Sensirion I have and printing the adapters as they are on the master branch in some Photocentric flex resin they seal perfectly well, I can still huck the PCB clean off the sensor if I blow hard enough. I don't have any 3/8" BSPT fittings to test with so it's possible the adaptor is bottoming out on the fitting before it makes a good enough seal, I have some 3/8" BSPT fittings coming soon so I can test that. 

The male adapter in #182 is a bit hard to install and remove, but it may come in handy when we want to install the system into an enclosure on a semi permanent basis where having adapters that won't come free when jostled will be necessary.

**Comment by Judoguy12** [comment]
Leak was identified through all 3dprinted adaptors either through the plastic or under the tape, I will be printing in resin to remedy this
![PXL_20211007_053652141](https://user-images.githubusercontent.com/30008485/136399175-66c61d47-42f5-4e33-8f64-38cabb94df11.jpg)
![PXL_20211007_053711347](https://user-images.githubusercontent.com/30008485/136399181-5e995cca-bc79-4e95-a5e3-f0d3f4eeb497.jpg)
![PXL_20211007_053740892](https://user-images.githubusercontent.com/30008485/136399187-c1e74c94-1f7b-48fe-85ce-bc1cb5af91b4.jpg)
![PXL_20211007_053812140](https://user-images.githubusercontent.com/30008485/136399190-6988534d-dabf-4d5e-9fac-58ef853bd427.jpg)
![PXL_20211007_053816350](https://user-images.githubusercontent.com/30008485/136399191-f01786e3-5ac2-4291-931c-f471f18c871a.jpg)
![PXL_20211007_053850102](https://user-images.githubusercontent.com/30008485/136399193-f165dbd1-d1c5-4cc8-9763-2b0a918a3ef5.jpg)
![PXL_20211007_053906353](https://user-images.githubusercontent.com/30008485/136399196-c79af43d-1879-44f6-beb5-a2be5c32ff5c.jpg)
![PXL_20211007_053911250](https://user-images.githubusercontent.com/30008485/136399197-c594a589-aad7-45a3-89b7-3ae5ca6e564f.jpg)

**Comment by darraghbr** [comment]
If this is just the FDM adapters then this is a duplicate of #176

**Comment by Judoguy12** [comment]
Solved by the resin adaptors![PXL_20211021_104231003.jpg](https://user-images.githubusercontent.com/30008485/138262396-3b880889-319f-4f79-a477-f6e7c1e3a174.jpg)

**Comment by darraghbr** [comment]
Closing and duplicate with #176
