### ISSUE TITLE
move python code for raspberry pi display to separate repo

### ISSUE THREAD

**Issue by capsulecorplab** [helpfulengineering/project-tetra#62]
The python for the raspberry pi display would be best maintained in a separate repo, as to not confuse its version number or LICENSE with the CAD, STL, & Drawing (a.k.a hardware) files.

This is really a two part task consisting of:
- [x] adding display code in https://github.com/tetrabiodistributed/project-tetra-display
- [ ] removing display code from https://github.com/tetrabiodistributed/project-tetra

**Comment by capsulecorplab** [comment]
Reopening, since display code still technically subsides in https://github.com/tetrabiodistributed/project-tetra/tree/master/02_Development/Display

**Comment by mmroden** [comment]
This has been done.  https://github.com/tetrabiodistributed/project-tetra-display/pull/1
