### ISSUE TITLE
P-TET-000004-0 RPi display frame Design change

### ISSUE THREAD

**Issue by Burhan-Q** [helpfulengineering/project-tetra#64]
- [x] Add 0.25 mm to current width on inside RPi display frame

**Comment by cyunis** [comment]
video with description of issue
[20200720_141340.mp4.zip](https://github.com/tetrabiodistributed/project-tetra/files/4963838/20200720_141340.mp4.zip)

**Comment by Burhan-Q** [comment]
@mechatroniks-git What material are you using to print this? The original dimensions for the part are shown in the image:
![image](https://user-images.githubusercontent.com/62214284/88335067-b47ce700-cd00-11ea-8b26-f85bf14c1c52.png)

I will add an additional 0.25mm as you mentioned, but would like to track what kind of material shrinkage we're seeing to avoid future issues.

**Comment by Burhan-Q** [comment]
@mechatroniks-git change has been made, ready for review. Going to move card to under review on project board.

**Comment by mechatroniks-git** [comment]
@mmroden printed it with PLA

**Comment by mechatroniks-git** [comment]
Since we already have a -0 STL in github, we need to bump the part number to a -1. 

Dimension change appears to be good.
![image](https://user-images.githubusercontent.com/57600622/88407883-a02ffd00-cd87-11ea-88d6-4167561706d2.png)

**Comment by Burhan-Q** [comment]
Understood. I will update part text, but @mechatroniks-git, when I save the new part should I create a new milestone for Rev 1 and update the part number to reflect the revision?

**Comment by mechatroniks-git** [comment]
I'd only save a milestone whenever you upload the file to git

**Comment by Burhan-Q** [comment]
Agreed (with a minor caveat). I think we have a running discussion of this topic [here](https://helpfulengineering.slack.com/archives/G012Q55KWN7/p1595612022005500) about that. I think once we've hammered out the details, I'll be working with @cyunis to formalize it into the GitHub Docs.

**Comment by mmroden** [comment]
less than a day to update, 2 days review

**Comment by mmroden** [comment]
to be printed by Mark, reviewed by Patrick

**Comment by mmroden** [comment]
will be printed in white

**Comment by Burhan-Q** [comment]
@mmroden ready for printing
[P-TET-000004-1.zip](https://github.com/tetrabiodistributed/project-tetra/files/4989315/P-TET-000004-1.zip)

**Comment by Burhan-Q** [comment]
@mmroden printed with a nice, uneven marbling; will reprint

![image](https://user-images.githubusercontent.com/62214284/88804139-80c81400-d17b-11ea-87f7-74ea6c595f4d.png)

**Comment by mechatroniks-git** [comment]
Ready to test part when handoff is made

**Comment by Burhan-Q** [comment]
> Ready to test part when handoff is made

@mmroden will you be able to get this part to @mechatroniks-git before/by next week? If not, recommend we move this ticket to Blocked (if there is no reply, I will move the ticket after 24 hours)

**Comment by Burhan-Q** [comment]
@mmroden delivered to @mechatroniks-git this past weekend. Assigning to @mechatroniks-git for review/approval when available.

**Comment by mechatroniks-git** [comment]
We will test this during assembly in the next few days
