### ISSUE TITLE
⇑ A-TET-001010-0 Tetra Valve with One Way Exploded

### ISSUE THREAD

**Issue by Burhan-Q** [helpfulengineering/project-tetra#76]
**Create exploded view:** A-TET-001010-0 Tetra Valve with One Way
- [x] Assigned _(specify assignees)_
- [x] Work in Progress _(move card on Project Board)_
- [x] Submit for Review _(assign reviewer, comment, & move on Project Board)_
- [x] Working on Review changes _(comment w/ list of changes and date)_
- [x] Review complete _(assigned reviewer comment with approved date)_

**Comment by Judoguy12** [comment]
21/07/2020 @mechatroniks-git

**Comment by Burhan-Q** [comment]
I'm not 100% on this, but I would think that since the o-ring is installed from the bottom side, you'd want to move it under that section of the valve. I say this since I think the idea of the drawings is to demonstrate how this would be assembled, so the parts should be positioned relative to how they'll be installed. Otherwise, I think this looks good

![image](https://user-images.githubusercontent.com/62214284/88431382-35eb7c80-cdc8-11ea-90bf-c87107b1d626.png)

**Comment by Judoguy12** [comment]
Did that not update? i had moved that 😓

**Comment by Judoguy12** [comment]
@Burhan-Q Should be fixed now

**Comment by Burhan-Q** [comment]
Exploded view looks ready for drawing #77 

Closing issue
