### ISSUE TITLE
Create Drawing Template

### ISSUE THREAD

**Issue by Burhan-Q** [helpfulengineering/project-tetra#95]
- [x] Assigned _(specify assignees)_
- [x] Work in Progress _(move card on Project Board)_
- [x] Submit for Review _(comment w/ date and assigned reviewer)_
- [ ] Working on Review changes _(comment w/ list of changes and date)_
- [ ] Final Review complete _(assigned reviewer comment with approved date)_

**Comment by Burhan-Q** [comment]
Status update: awaiting logo design from @thehannahfink and @cyunis for adding to template

**Comment by Burhan-Q** [comment]
@jgrano Assigned as Reviewer

**Comment by mechatroniks-git** [comment]
Drawing templates needed (mostly just notes changes)
- FDM Part Template (perhaps make it 2 sheets, 2nd sheet for heated inserts/post processing)
- SLA Part Template
- Assembly Template

Notes on Assembly Template:
```
Notes (unless otherwise specified):
1. This drawing is construed as information only, it is complete only to the degree necessary to illustrate a system definition for assembly

```

**Comment by mechatroniks-git** [comment]
@Judoguy12 I updated the template
- Replaced logo with a image with transparent background I created. (@thehannahfink, do you have a set of PNGs with high resolution and transparent backgrounds?)
- Added units, tolerances and 3rd angle projection box

todo:
Look at replacing the font with Helvitica Bold?
update notes
add open source license info?

**Comment by Judoguy12** [comment]
Ready for review @jgrano 3/8/2020

**Comment by mechatroniks-git** [comment]
Title block needs help, logo looks rough, @thehannahfink can we do SVG art? [Fusion ](https://knowledge.autodesk.com/support/fusion-360/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-import-SVG-files-in-Fusion-360.html)allows it to be added. 
![image](https://user-images.githubusercontent.com/57600622/89218870-a2fad100-d583-11ea-9f8e-4c4bd76e0052.png)
![image](https://user-images.githubusercontent.com/57600622/89219349-74c9c100-d584-11ea-8d07-5c331ed29787.png)

Copyright notice - @capsulecorplab does this look right?
![image](https://user-images.githubusercontent.com/57600622/89219266-4f3cb780-d584-11ea-863f-6b2f2c465b8a.png)

**Comment by Judoguy12** [comment]
@mechatroniks-git Fusion would not allow the SVG to be added I had to convert to transparent PNG

**Comment by Judoguy12** [comment]
@mechatroniks-git fixed address appearing

**Comment by capsulecorplab** [comment]
@mechatroniks-git copyright notice looks good!

**Comment by mechatroniks-git** [comment]
@Judoguy12 we need to place our web address somewhere

**Comment by Judoguy12** [comment]
@mechatroniks-git Is that better or shall i remove the company name above the web address
![image](https://user-images.githubusercontent.com/30008485/89448891-2b2dd180-d750-11ea-866c-0de5245d2199.png)

**Comment by mechatroniks-git** [comment]
The TETRA BIO DISTRIBUTED is redundant and doesn't match the style guidelines, so best to remove that
The unnecessary blank-space above & below the logo/name should be eliminated.
Maybe swap the logo with the website or combine them in 1 box?

**Comment by Judoguy12** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/30008485/89511122-63bdc180-d7c9-11ea-80e6-cc39953e74c4.png)

**Comment by thehannahfink** [comment]
[There is a version on GitHub with just the logo and no title](https://github.com/tetrabiodistributed/tetrabiodistributed.github.io/blob/dev/assets/logo/black/tetra_logo_black_100_x_100_px.svg) if that's the logo version you want. The website should be all on one line, so maybe make the font size small enough to fit without a line break. I liked the website better on far-right column. Should be underneath the Project block in its own "website" block though.
